// <auto-generated />
using System;
using InterviewTracker.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InterviewTracker.Migrations
{
    [DbContext(typeof(ITrackerDbContext))]
    [Migration("20260121030553_AddMorePropertiesToEmployer")]
    partial class AddMorePropertiesToEmployer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("InterviewTracker.Models.Employer", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("companyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal?>("ctcOffered")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime?>("dateOfJoining")
                        .HasColumnType("DATE");

                    b.Property<string>("interviewLevel")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("interviewStatus")
                        .HasColumnType("longtext");

                    b.Property<string>("location")
                        .HasColumnType("longtext");

                    b.Property<string>("notes")
                        .HasColumnType("longtext");

                    b.Property<byte[]>("offerLetter")
                        .HasColumnType("longblob");

                    b.Property<string>("offeredRole")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.Property<string>("websiteLink")
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("userId");

                    b.ToTable("Employers");
                });

            modelBuilder.Entity("InterviewTracker.Models.HRDetail", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("emailId")
                        .HasColumnType("longtext");

                    b.Property<int>("employerId")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("phoneNumber")
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("employerId")
                        .IsUnique();

                    b.ToTable("HrDetails");
                });

            modelBuilder.Entity("InterviewTracker.Models.Names", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("Names");
                });

            modelBuilder.Entity("InterviewTracker.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("age")
                        .HasColumnType("int");

                    b.Property<string>("currentCompany")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("googleId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("phoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("profilePictureUrl")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<byte[]>("resume")
                        .HasColumnType("longblob");

                    b.Property<string>("skills")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("id");

                    b.HasIndex("email")
                        .IsUnique();

                    b.HasIndex("googleId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("InterviewTracker.Models.Employer", b =>
                {
                    b.HasOne("InterviewTracker.Models.User", "user")
                        .WithMany("employers")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("InterviewTracker.Models.HRDetail", b =>
                {
                    b.HasOne("InterviewTracker.Models.Employer", "employer")
                        .WithOne("hrDetail")
                        .HasForeignKey("InterviewTracker.Models.HRDetail", "employerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("employer");
                });

            modelBuilder.Entity("InterviewTracker.Models.Employer", b =>
                {
                    b.Navigation("hrDetail")
                        .IsRequired();
                });

            modelBuilder.Entity("InterviewTracker.Models.User", b =>
                {
                    b.Navigation("employers");
                });
#pragma warning restore 612, 618
        }
    }
}
